// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BatteryInfo;

@interface BatteryInfo : NSObject
+ (instancetype)makeWithBatteryPercentage:(nullable NSString *)batteryPercentage;
@property(nonatomic, copy, nullable) NSString * batteryPercentage;
@end

/// The codec used by BatteryInfoApi.
NSObject<FlutterMessageCodec> *BatteryInfoApiGetCodec(void);

@protocol BatteryInfoApi
/// This abstract function will contain code that performs communication
/// with native platforms, sending in [FileData] as a message and receiving [Response] as a response.
///
/// @return `nil` only when `error != nil`.
- (nullable BatteryInfo *)getbatteryInformationWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BatteryInfoApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BatteryInfoApi> *_Nullable api);

NS_ASSUME_NONNULL_END
